import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./globals.css";

import { Metadata } from "next";
import { Header } from "@/components";
import Footer from "@/components/Footer/Footer";
import { ProductProvider } from "@/components/Providers/ContextProvider";
import { prisma } from "../../../db";
import { TeaProduct } from "@/types/tea-product.type";
import { ProductCartProvider } from "@/components/Providers/ProductCartProvider";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Jasmine Dragon",
    template: "%s - Jasmine Dragon",
  },
  description: "Generated by Next.js",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const teas: TeaProduct[] = await prisma.product.findMany();
  // console.log(teas);
  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className="overflow-x-hidden scroll-smooth"
      >
        <ProductProvider products={teas}>
          <NextIntlClientProvider messages={messages}>
            <ProductCartProvider>
              <Header />
              {children}
              <Footer />
            </ProductCartProvider>
          </NextIntlClientProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
